name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      
      # - name: action-git-diff-suggestions
        # You may pin to the exact commit or the version.
        # uses: getsentry/action-git-diff-suggestions@8c75946d0d7bbe80a92cf3579d544321512c30b7
      - uses: getsentry/action-git-diff-suggestions@v1
        with:
          # github token
          # github-token: # optional
          # The message to prepend the review suggestion
          message: This is a test
  # environment: # optional which determines the environment the job runs on
  # defaults: # set default values for the job 
